### ISSUE TITLE
Unable to setup pays module

### ISSUE THREAD

**Issue by ludekvesely** [PavelStrejcek/PrestaShop-module-Pays#1]
Hi @PavelStrejcek,

thank you for developing module for Prestashop. I'm using Prestashop 1.6.1.17 and I'm not able to install your module properly. During installation I'm getting the following exception:

![https___www_kolinokram_cz_admin0375_index_php_controller_AdminModules_token_72131d7ce304d497c1195d4c933c47af_install_pays_ps_tab_module_payments_gateways_module_name_pays_ps_anchor_Pays_ps](https://user-images.githubusercontent.com/12381709/77748966-853fbd00-7021-11ea-86cb-77794e3e8ba2.png)

After installation, the module seems to be installed and I'm able to configure it. But I don't see new order's states mentioned in the documentation, neither I don't see pays as a new payment method.

Could you please help me to fix this issue and set up your module properly? Thank you!

**Comment by PavelStrejcek** [comment]
Hi @ludekvesely,

This issue seems to be out of the module.
An overriding class is used:
override/classes/Launguage.php

This is not part of PrestaShop 1.6.1.17.
